using System.Diagnostics;
using SkiaSharp;
using ZXing;
using ZXing.SkiaSharp.Rendering;
using ZXing.SkiaSharp;
using System.Buffers.Text;

namespace WeReadTool.Tests
{
    public class QrCodeTest
    {
        [Fact]
        public void Decode()
        {
            var base64 = "iVBORw0KGgoAAAANSUhEUgAAAZAAAAGQCAIAAAAP3aGbAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAHUUlEQVR4nO3dS27kOBBAQdfA979y9Q3GbIDZ6VeKWBv6lfzADVOv9/v9BVDw3/YFAJwSLCBDsIAMwQIyBAvIECwgQ7CADMECMgQLyBAsIEOwgAzBAjIEC8gQLCBDsIAMwQIyBAvIECwgQ7CADMECMgQLyBAsIEOwgAzBAjIEC8gQLCDj+/oRX6/X9WN+mPf7ffJn50/y8IB/JfE7nt/49YeZeD67Jl5LKywgQ7CADMECMgQLyBAsIEOwgAzBAjIEC8gQLCBDsIAMwQIyBAvIECwg4/60hnMTm7kXXd++vziKYMLE7SRGJnjPL7LCAjIEC8gQLCBDsIAMwQIyBAvIECwgQ7CADMECMgQLyBAsIEOwgAzBAjI2pzWcW9wgnthqP3GRj73xRd7zH1lhARmCBWQIFpAhWECGYAEZggVkCBaQIVhAhmABGYIFZAgWkCFYQEZj8/MzJT5AP2Hio/YTZ+ffs8ICMgQLyBAsIEOwgAzBAjIEC8gQLCBDsIAMwQIyBAvIECwgQ7CADMECMkxr+L0mxgYsjjeYGD6xO9eBf88KC8gQLCBDsIAMwQIyBAvIECwgQ7CADMECMgQLyBAsIEOwgAzBAjIEC8hoTGuYmFvwSSYGISyON3jsZAXv+Y+ssIAMwQIyBAvIECwgQ7CADMECMgQLyBAsIEOwgAzBAjIEC8gQLCBDsICMzWkNj92Uf2h3BsP1YyYucoL3/CIrLCBDsIAMwQIyBAvIECwgQ7CADMECMgQLyBAsIEOwgAzBAjIEC8gQLCDjdb7fnV9rYrzBxNmv8/Y+jRUWkCFYQIZgARmCBWQIFpAhWECGYAEZggVkCBaQIVhAhmABGYIFZDQ2Py9+DH3C4XUmLvJr+zq37P7jLG53391pb4UFZAgWkCFYQIZgARmCBWQIFpAhWECGYAEZggVkCBaQIVhAhmABGYIFZGxOa/CJ839v4pkvDp+Y+B2vX2dlrsN1pjUAjyZYQIZgARmCBWQIFpAhWECGYAEZggVkCBaQIVhAhmABGYIFZAgWkPF9/YiVTfnXLW6Ln3D+zBM3/mEzGB7LCgvIECwgQ7CADMECMgQLyBAsIEOwgAzBAjIEC8gQLCBDsIAMwQIyBAvIeF3fdL44reH81Ltb7RPjDa6rjDc4/HUmpllUHtEiKywgQ7CADMECMgQLyBAsIEOwgAzBAjIEC8gQLCBDsIAMwQIyBAvIECwg4/60hr849+2hBRMb6CckJmQsmngnE4/ok/4Zv2ZuxwoLyBAsIEOwgAzBAjIEC8gQLCBDsIAMwQIyBAvIECwgQ7CADMECMr4Xz7241XP3O+PXP4b+WLY0/yjxiM5ZYQEZggVkCBaQIVhAhmABGYIFZAgWkCFYQIZgARmCBWQIFpAhWECGYAEZ96c1LI43mLA412HiSSZ82ICBx/6OE6ywgAzBAjIEC8gQLCBDsIAMwQIyBAvIECwgQ7CADMECMgQLyBAsIEOwgIzX4gZx4w3+X2VowTMf5sRdL77Alf8dKywgQ7CADMECMgQLyBAsIEOwgAzBAjIEC8gQLCBDsIAMwQIyBAvIECwg4/v6ESe2fR8e8/oBh455XeIiK8MnDn3Y7SRGbnxZYQEhggVkCBaQIVhAhmABGYIFZAgWkCFYQIZgARmCBWQIFpAhWECGYAEZr8ou7Qd67EiJCRMP87rEL777O1phARmCBWQIFpAhWECGYAEZggVkCBaQIVhAhmABGYIFZAgWkCFYQMbmp+of63D76O4u0+tnT2w/Prd7O9fPfn7A3Ru3wgIyBAvIECwgQ7CADMECMgQLyBAsIEOwgAzBAjIEC8gQLCBDsIAMwQIy7k9rOJfYlH/u+piKiW3xiY/aJwZ+fNjbm3gxvqywgBDBAjIEC8gQLCBDsIAMwQIyBAvIECwgQ7CADMECMgQLyBAsIEOwgIzNaQ3nFjeIJzbl726gP3xEE8Mnzp2f3ayIX3vqLyssIESwgAzBAjIEC8gQLCBDsIAMwQIyBAvIECwgQ7CADMECMgQLyBAsIKMxreGZzrfFTwwY2D37dddvZ/f5XB99sTtL45wVFpAhWECGYAEZggVkCBaQIVhAhmABGYIFZAgWkCFYQIZgARmCBWQIFpBhWsPvNbGB/vyYiRkM5xbHG0xIDJ+YmOtghQVkCBaQIVhAhmABGYIFZAgWkCFYQIZgARmCBWQIFpAhWECGYAEZjc3Pu1/H3rJ719fPnvhi+4Tdj9r7VD3ADsECMgQLyBAsIEOwgAzBAjIEC8gQLCBDsIAMwQIyBAvIECwgQ7CAjFdiU/6H+bDhE4lffPGZJ57PBJ+qBx5NsIAMwQIyBAvIECwgQ7CADMECMgQLyBAsIEOwgAzBAjIEC8gQLCDj/rQGgCFWWECGYAEZggVkCBaQIVhAhmABGYIFZAgWkCFYQIZgARmCBWQIFpAhWECGYAEZggVkCBaQIVhAhmABGYIFZAgWkCFYQIZgARmCBWQIFpAhWECGYAEZggVk/AE1l4Yn+gTVPgAAAABJRU5ErkJggg==";

            var re = Ray.Infrastructure.BarCode.BarCodeHelper.DecodeByBase64Str(base64);

            Assert.True(re.Text == "Hello World");
        }

        [Fact]
        public void Encode()
        {
            var text = "Hello World";

            SKBitmap? bitmap = Ray.Infrastructure.BarCode.BarCodeHelper.Encode(text);

            Ray.Infrastructure.BarCode.BarCodeHelper.PrintQrCode(bitmap,
                onCharPrintProcess: c => Debug.Write(c),
                onRowPrintProcessed: () => Debug.WriteLine(""));
        }
    }
}